language: php

php:
  - 5.6
  - 7.0
  - 7.1

install:
  - composer self-update
  - composer global require fxp/composer-asset-plugin:~1.0
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover


after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
