name: build

on: [push, workflow_dispatch, pull_request]

env:
    COMPOSE_PROJECT_NAME: yii2-yandex-market-yml
    COMPOSE_FILE: tests/docker-compose.yml
jobs:
    phpunit:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ 56, 70, 71, 72, 73, 74 ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: PHP Unit tests for PHP ${{ matrix.php }}
                run: make test${{ matrix.php }}
